apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
  namespace: stackgres
spec:
  selector:
    matchLabels:
      app: timescaledb
  serviceName: "timescaledb"
  replicas: 1
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescaledb-password
                  key: password
          volumeMounts:
            - name: timescaledb-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: timescaledb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
